"""add status to rescue alert

Revision ID: 34bdb66c5eb7
Revises: e99b249e9d1b
Create Date: 2025-07-10 15:50:51.760925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bdb66c5eb7'
down_revision = 'e99b249e9d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rescue_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('manual_status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rescue_alert', schema=None) as batch_op:
        batch_op.drop_column('manual_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
