"""Add status and manual_status to LostPetReport

Revision ID: 4ee0ae19d1bb
Revises: 
Create Date: 2025-07-10 14:59:08.277506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee0ae19d1bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_pet_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('manual_status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_pet_report', schema=None) as batch_op:
        batch_op.drop_column('manual_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
