"""Add manual_status to AdoptionRequest

Revision ID: 89d623f5b20a
Revises: 4ee0ae19d1bb
Create Date: 2025-07-10 15:15:15.017317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d623f5b20a'
down_revision = '4ee0ae19d1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.drop_column('manual_status')

    # ### end Alembic commands ###
